Sprint 2/step 1
aatvel/stellar-burgers pull request #5
Opened 2022-11-14 14:01 UTC by aatvel

2022-11-14 20:29 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **очень хорошую** работу по добавлению контекста в ваш проект, в плане работы с ним у вас всё корректно работает и исполнено в коде, так держать 👍 

Однако, для успешной сдачи работы вам необходимо внимательно ознакомиться с указанными в рамках ревью комментариями и провести корректировки, обратив особое внимание на следующие моменты:

**Нужно исправить по вёрстке:**

- Между верхней булкой и первым ингредиентом присутствует лишнее пустое пространство (https://disk.yandex.ru/i/N2-ofzvqpxzHMw), следует убрать его;
- Отсутствует отступ между переключателями категории ингредиентов и списком, следует его добавить (https://disk.yandex.ru/i/AqdW9fOs-85pjA);
- Дизайн заголовка не соответствует макету, следует добавить правильный задний фон (он другого цвета на макете) и убрать фон у ссылок; (https://disk.yandex.ru/i/o36Go4YcNolX1w)
- Присутствует вертикальный скролл всего сайта, его следует также убрать. Скроллится должны только списки ингредиентов и начинка бургера;
- Цена бургера наезжает на кнопку оформления (https://disk.yandex.ru/i/eKVmMSI1rnfx-A);
- У модального окна, согласно дизайну, есть закругления по бокам, следует их добавить (https://disk.yandex.ru/i/uQohhS5MShTo-A);

**Нужно исправить по коду:**

- При выполнении запроса следует обеспечить проверку его успешности, ошибка в методе `catch` появится только, если возникли проблемы на уровне браузера;
- Следует скорректировать использование функции `map` в рамках формирования списка начинки у бургера, согласно её спецификации и предназначению (см. BurgerConstructor);

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +  let orderId = []
🟡 **Можно улучшить:**

**Здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как `const`

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    orderId.push(element._id)
🟡 **Можно улучшить:**

Массив с идентификаторами ингредиентов `orderId` и объект для fetch `requestOptions` целесообразно формировать в момент вызова функции `handleSubmitOrder`, чтобы не генерировать их при каждом рендере компонента (что использует дополнительную память и проводит лишние вычисления, т.к. не факт что на текущей итерации формирования бургера мы отправим его на сервер)

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +      .then((res) => res.json())
🔴 **Нужно исправить:**

При выполнении запроса следует обеспечить проверку его успешности, как в методе catch, когда он появится только, если возникли проблемы на уровне браузера (например нет сети) так и перед преобразованием результата в JSON нужно вызвать метод res.ok, что обеспечит проверку ошибок со стороны сервера (см. https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch)

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +        console.log(result);
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +            handleSubmitOrder()
🟡 **Можно улучшить:**

Имеет смысл сначала вызывать API метод, а затем открывать окно заказа => так быстрее получим результат :)

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +  ingredientsOrder.map((element) => {if (element.type !== 'bun'){
🔴 **Нужно исправить:**

Функция `map` возвращает по результату новый массив на основе указанного вами условия (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map), поэтому текущее её использование некорректно. Есть два варианта исправления: 
1) Заменить на более подходящий в текущей реализации `forEach` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach);
2) Возвращать из внутренней функции значение `return element._id;` и присвоить результат `const orderId = ingredientsOrder.map(...)` - тогда `map` будет использоваться корректно

2022-11-14 20:29 UTC, randomroot commented on src/components/order-details/order-details.js
> +  odrerNumber: PropTypes.number
🔴 **Нужно исправить:**

Из-за небольшой орфографической ошибки `PropTypes` являются некорректными, следует исправить название ключа

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +            if(element.type !== 'bun'){
🟡 **Можно улучшить:**

В текущей реализации вы фильтруете массив от булок по факту 2 раза: здесь и в момент вычисления цены. Поэтому имеет смысл результат такой фильтрации записать в отдельную константу и воспользоваться функцией `filter`:

```jsx
const notBunIngredients= ingredients.filter((item) => item.type !== 'bun'))
...
{ notBunIngredients.map(...) }
```

А стоимость заказа затем можно будет вычислить с помощью удобной функции `reduce` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2022-11-14 20:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +            if(element.type !== 'bun'){
🟡 **Можно улучшить:**

В текущей реализации вы фильтруете массив от булок по факту 2 раза: здесь и в момент вычисления цены. Поэтому имеет смысл результат такой фильтрации записать в отдельную константу и воспользоваться функцией `filter`:

```jsx
const notBunIngredients= ingredients.filter((item) => item.type !== 'bun'))
...
{ notBunIngredients.map(...) }
```

2022-11-14 20:29 UTC, randomroot commented on src/components/app/app.js
>        {ingredientModal && (
🟡 **Можно улучшить:**

Модальные окна не относятся ко всему приложению в целом, а конкретно к его отдельным компонентам, с которыми они связаны информацией, поэтому следует перенести их именно туда.
Это поможет упростить читабельность вашего кода (получится быстрее найти нужный код и уменьшит размер App.jsx, который лучше поддерживать в простом состоянии, как одну из точек входа) и уменьшит кол-во пропсов передаваемых в компоненты списка ингредиентов и конструктора.

2022-11-14 20:29 UTC, randomroot commented on src/components/app/app.js
>  function PreLoader() {
🟡 **Можно улучшить:**

В рамках одного файла целесообразно размещать только один компонент, чтобы упростить тестирование и улучшить читабельность кода

2022-11-14 20:29 UTC, randomroot commented on src/components/app/app.js
>    const [ingredientModal, setIngredientModal] = React.useState(false);
🟡 **Можно улучшить:**

В этой переменной и в переменной ниже `orderModal` на самом деле нет необходимости, т.к. можно ориентироваться по наличию значений в `ingredient` и `order` соответственно - если там оно есть, значит пора открывать окно, а если пустота - убираем его :)

2022-11-15 15:41 UTC, aatvel commented
added reviewers comments

2022-11-15 20:50 UTC, randomroot approved these changes
🟡 **Здравствуйте!** 

Вы успешно улучшили ваш код и исправили часть указанных в рамках первой итерации моментов, однако некоторые из них всё еще присутствуют в проекте.

В следующих спринтах, вероятнее всего, они станут снова критичными, поэтому предлагаю вам ознакомиться с ними. Тем не менее, согласно правилам спринта, ваша работа **принимается автоматически** на 2-ой итерации, поэтому все корректировки следует проводить в рамках следующего PR.

👀 **Вёрстка:**

- Появилась горизонтальная прокрутка экрана, вертикальная осталась (пропадает только в полноэкранном режиме, но пользователя сложно замотивировать им пользоваться 😺 ) (https://disk.yandex.ru/i/Fbe6ozFxHayrxQ);
- Ширину хедера следует сделать равной ширине контента вашего проекта (не шире, чем пространство под ним, где список ингредиентов и конструктор бургера);
- Проблема с наезжанием стоимости на кнопку создания заказа осталась при больших значениях (https://disk.yandex.ru/i/qj38BaFPdCKpxQ);

⚡ **Код:**

- Следует добавить `catch` к выполняемым запросам, чтобы отследить ошибки на уровне сети/браузера;
- Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса;

**Желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-15 20:50 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    fetch("https://norma.nomoreparties.space/api/orders", requestOptions)
🔴 **Нужно исправить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/orders`

2022-11-28 10:05 UTC, merged